deployment:
  replicas: 2
  imageURL: "222634367824.dkr.ecr.us-east-1.amazonaws.com/expense/dev/frontend"
  tag: "1"
hpa:
  cpuUtilization: 15
tgb:
  arn: "arn:aws:elasticloadbalancing:us-east-1:222634367824:loadbalancer/app/expense-dev-ingress-alb/d7b521fba131a1f0"